FROM  python:3.9.7-buster
WORKDIR /app
COPY ./requirements.txt /app
RUN pip install -r requirements.txt
COPY ./ /app
EXPOSE 8888
CMD jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser --allow-root